[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = { version = "2.8", features = ["tokio-runtime"] }
tokio = { version = "1.37", features = ["full"] }
dotenvy = "0.15"
